name: BSD

on: [push, pull_request]

jobs:
  test-bsd:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - { name: freebsd, version: '14.3' }
          - { name: netbsd, version: '10.1' }
          - { name: openbsd, version: '7.8' }
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies and build on ${{ matrix.os.name }} ${{ matrix.os.version }}
        uses: cross-platform-actions/action@master
        with:
          operating_system: ${{ matrix.os.name }}
          version: ${{ matrix.os.version }}
          shell: bash
          run: |
            uname -a
            echo `sysctl -n hw.ncpu`
            case "${{ matrix.os.name }}" in
              freebsd)
                ASSUME_ALWAYS_YES=yes sudo pkg install -y cgal gmp mpfr boost-libs cmake ninja curl nlohmann-json
                ;;
              netbsd)
                sudo pkgin -y update
                sudo pkgin -y install cgal gmp mpfr boost cmake ninja-build curl nlohmann-json
                ;;
              openbsd)
                sudo pkg_add cgal gmp gmpxx mpfr boost cmake ninja curl nlohmann-json
                ;;
            esac

            export CGAL_VERSION=6.1
            curl -L -o CGAL-${CGAL_VERSION}.tar.gz "https://github.com/CGAL/cgal/archive/refs/tags/v${CGAL_VERSION}.tar.gz"
            tar xzf CGAL-${CGAL_VERSION}.tar.gz

            cmake -GNinja -S . -B build -DSFCGAL_BUILD_TESTS=ON -DCGAL_DIR=CGAL-${CGAL_VERSION}
            cmake --build build -j `sysctl -n hw.ncpu`
            ctest -VV --test-dir build

  test-macos:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew update
          brew install boost cgal gmp mpfr nlohmann-json

      - name: Build
        run: |
          cmake -DSFCGAL_BUILD_TESTS=ON -S . -B build
          cmake --build build
          ctest -VV --test-dir build
